#! /usr/bin/perl
use JSON;
($version_manifest_url,$manual_version)=@ARGV;
if(!$version_manifest_url)
{
	die(
"NameProvider Data Generator, v1.1
https://github.com/bilintsui/nameprovider-data-generator

Usage: $0 <version_manifest_url> [manual_version]

<version_manifest_url>	URL of a qualified version manifest. Usually fine to use the official one.
			Official: https://piston-meta.mojang.com/mc/game/version_manifest.json
[manual_version]	Optional, the exact game version used to generate data. Defaults to 0.
			Number based on the order of versions in the file provided, start with 0.
");
}
if(!$manual_version)
{
	$manual_version=0;
}
$version_manifest_raw=readpipe("curl -s '${version_manifest_url}'");
$version_manifest=decode_json($version_manifest_raw);
$version_id=$version_manifest->{versions}[$manual_version]->{id};
$version_time=$version_manifest->{versions}[$manual_version]->{time};
$version_json_url=$version_manifest->{versions}[$manual_version]->{url};
$version_json_raw=readpipe("curl -s '$version_json_url'");
$version_json=decode_json($version_json_raw);
$client_jar_url=$version_json->{downloads}->{client}->{url};
system("curl -o 'client.jar' '$client_jar_url'; unzip -qq -d tmp client.jar; mv tmp/assets/minecraft/lang/en_us.json .; rm -r tmp client.jar");
system("grep -P '^\\s+' en_us.json | sed -e 's/^\\s*\"//' -e 's/\":\\s*/\\t/' -e 's/\",\$/\"/' | sort > col1.txt; rm en_us.json");
$assetindex_url=$version_json->{assetIndex}->{url};
$assetindex_raw=readpipe("curl -s '$assetindex_url'");
$assetindex=decode_json($assetindex_raw);
$lang_zhcn_hash=$assetindex->{objects}->{'minecraft/lang/zh_cn.json'}->{hash};
$lang_zhcn_url='https://resources.download.minecraft.net/'.substr($lang_zhcn_hash,0,2).'/'.$lang_zhcn_hash;
$lang_zhtw_hash=$assetindex->{objects}->{'minecraft/lang/zh_tw.json'}->{hash};
$lang_zhtw_url='https://resources.download.minecraft.net/'.substr($lang_zhtw_hash,0,2).'/'.$lang_zhtw_hash;
$lang_zhhk_hash=$assetindex->{objects}->{'minecraft/lang/zh_hk.json'}->{hash};
$lang_zhhk_url='https://resources.download.minecraft.net/'.substr($lang_zhhk_hash,0,2).'/'.$lang_zhhk_hash;
system("curl -o 'zh_cn.json' '$lang_zhcn_url'");
system("grep -P '^\\s+' zh_cn.json | sed -e 's/^\\s*\"//' -e 's/\":\\s*/\\t/' -e 's/\",\$/\"/' | sort > col2.txt; rm zh_cn.json");
system("curl -o 'zh_tw.json' '$lang_zhtw_url'");
system("grep -P '^\\s+' zh_tw.json | sed -e 's/^\\s*\"//' -e 's/\":\\s*/\\t/' -e 's/\",\$/\"/' | sort > col3.txt; rm zh_tw.json");
system("curl -o 'zh_hk.json' '$lang_zhhk_url'");
system("grep -P '^\\s+' zh_hk.json | sed -e 's/^\\s*\"//' -e 's/\":\\s*/\\t/' -e 's/\",\$/\"/' | sort > col4.txt; rm zh_hk.json");
system("./join.sh; rm col1.txt col2.txt col3.txt col4.txt");
open DSTFD, ">output_$version_id.txt";
print DSTFD "-- version: $version_id\n-- asset: $assetindex_url ($version_time)\nreturn {\n";
close DSTFD;
system("cat tmp.txt >> output_$version_id.txt; rm tmp.txt");
open DSTFD, ">>output_$version_id.txt";
print DSTFD "}\n";
close DSTFD;
