#! /bin/bash
# NameProvider Data Generator, v2.5

# Lua header
echo 'return {' > result.lua

# Lua data table
awk '{print $0}' en_us.json | sed 1d | tac | sed 1d | tac | sed -E -e 's/^\s+"//' -E -e 's/"\s*:\s*/\t/' -E -e 's/,?$//' | sort -V | uniq | tee en_us.list | awk -F '\t' '{print $1}' > en_us.keys
awk '{print $0}' zh_cn.json | sed 1d | tac | sed 1d | tac | sed -E -e 's/^\s+"//' -E -e 's/"\s*:\s*/\t/' -E -e 's/,?$//' | sort -V | uniq | tee zh_cn.list | awk -F '\t' '{print $1}' > zh_cn.keys
awk '{print $0}' zh_tw.json | sed 1d | tac | sed 1d | tac | sed -E -e 's/^\s+"//' -E -e 's/"\s*:\s*/\t/' -E -e 's/,?$//' | sort -V | uniq | tee zh_tw.list | awk -F '\t' '{print $1}' > zh_tw.keys
awk '{print $0}' zh_hk.json | sed 1d | tac | sed 1d | tac | sed -E -e 's/^\s+"//' -E -e 's/"\s*:\s*/\t/' -E -e 's/,?$//' | sort -V | uniq | tee zh_hk.list | awk -F '\t' '{print $1}' > zh_hk.keys

diff en_us.keys zh_cn.keys | grep -P '^>' | sed 's/^> //' | awk '{print "grep -P \"^"$0"\\t\" zh_cn.list"}' | sed "s/\"/'/g" | bash | grep -vFf - zh_cn.list > zh_cn
diff en_us.keys zh_cn.keys | grep -P '^<' | sed 's/^< //' | awk '{print "grep -P \"^"$0"\\t\" en_us.list"}' | sed "s/\"/'/g" | bash | grep -Ff - en_us.list >> zh_cn

diff en_us.keys zh_tw.keys | grep -P '^>' | sed 's/^> //' | awk '{print "grep -P \"^"$0"\\t\" zh_tw.list"}' | sed "s/\"/'/g" | bash | grep -vFf - zh_tw.list > zh_tw
diff en_us.keys zh_tw.keys | grep -P '^<' | sed 's/^< //' | awk '{print "grep -P \"^"$0"\\t\" en_us.list"}' | sed "s/\"/'/g" | bash | grep -Ff - en_us.list >> zh_tw

diff en_us.keys zh_hk.keys | grep -P '^>' | sed 's/^> //' | awk '{print "grep -P \"^"$0"\\t\" zh_hk.list"}' | sed "s/\"/'/g" | bash | grep -vFf - zh_hk.list > zh_hk
diff en_us.keys zh_hk.keys | grep -P '^<' | sed 's/^< //' | awk '{print "grep -P \"^"$0"\\t\" en_us.list"}' | sed "s/\"/'/g" | bash | grep -Ff - en_us.list >> zh_hk

join -t $'\t' <(sort -V en_us.list | uniq) <(sort -V zh_cn | uniq) | join -t $'\t' - <(sort -V zh_tw | uniq) | join -t $'\t' - <(sort -V zh_hk | uniq) > result.list

sort -V en_us.keys | uniq | awk '{print "grep -P \"^"$0"\\t\" result.list"}' | sed "s/\"/'/g" | bash | sed -e "s/\t/' ] = { /" -e 's/\t/, /g' | awk "{print \"\\t[ '\"\$0\" },\"}" >> result.lua

# Lua footer
echo '}' >> result.lua

# Cleanup
rm *.keys *.list zh_cn zh_tw zh_hk
