#! /bin/bash
# NameProvider Data Generator, v2.5

# Lua header
echo 'return {' > result.lua

# Lua data table
awk '{print $0}' en_us.json | sed 1d | tac | sed 1d | tac | sed -E -e 's/^\s+"//' -E -e 's/"\s*:\s*/\t/' -E -e 's/,?$//' | sort -V | uniq | tee en_us.list | awk -F '\t' '{print $1}' > en_us.keys
awk '{print $0}' lzh.json | sed 1d | tac | sed 1d | tac | sed -E -e 's/^\s+"//' -E -e 's/"\s*:\s*/\t/' -E -e 's/,?$//' | sort -V | uniq | tee lzh.list | awk -F '\t' '{print $1}' > lzh.keys

diff en_us.keys lzh.keys | grep -P '^>' | sed 's/^> //' | awk '{print "grep -P \"^"$0"\\t\" lzh.list"}' | sed "s/\"/'/g" | bash | grep -vFf - lzh.list > lzh
diff en_us.keys lzh.keys | grep -P '^<' | sed 's/^< //' | awk '{print "grep -P \"^"$0"\\t\" en_us.list"}' | sed "s/\"/'/g" | bash | grep -Ff - en_us.list >> lzh

join -t $'\t' <(sort -V en_us.list | uniq) <(sort -V lzh | uniq) > result.list

sort -V en_us.keys | uniq | awk '{print "grep -P \"^"$0"\\t\" result.list"}' | sed "s/\"/'/g" | bash | sed -e "s/\t/' ] = { /" -e 's/\t/, /g' | awk "{print \"\\t[ '\"\$0\" },\"}" >> result.lua

# Lua footer
echo '}' >> result.lua

# Cleanup
rm *.keys *.list lzh
