#! /bin/bash
# NameProvider Data Generator, v2.0

# Prep
curl -Lo version_manifest.json https://piston-meta.mojang.com/mc/game/version_manifest.json
jq .versions[0].url version_manifest.json | xargs curl -Lo version.json
jq .downloads.client.url version.json | xargs curl -Lo client.jar
unzip client.jar assets/minecraft/lang/en_us.json
mv assets/minecraft/lang/en_us.json .
rm -r assets
jq .assetIndex.url version.json | xargs curl -Lo assets.json
jq .objects assets.json | jq 'to_entries|.[]|select(.key=="minecraft/lang/zh_cn.json")|.value' | jq .hash | sed 's/"//g' | awk '{print "curl -Lo zh_cn.json https://resources.download.minecraft.net/"substr($0,1,2)"/"$0}' | bash
jq .objects assets.json | jq 'to_entries|.[]|select(.key=="minecraft/lang/zh_tw.json")|.value' | jq .hash | sed 's/"//g' | awk '{print "curl -Lo zh_tw.json https://resources.download.minecraft.net/"substr($0,1,2)"/"$0}' | bash
jq .objects assets.json | jq 'to_entries|.[]|select(.key=="minecraft/lang/zh_hk.json")|.value' | jq .hash | sed 's/"//g' | awk '{print "curl -Lo zh_hk.json https://resources.download.minecraft.net/"substr($0,1,2)"/"$0}' | bash

# Lua headers
echo -n '-- version: ' > result.lua
jq .versions[0].id version_manifest.json | sed 's/"//g' >> result.lua
echo -n '-- asset: ' >> result.lua
jq .assetIndex.url version.json | sed 's/"//g' | tr '\n' ' ' >> result.lua
echo -n '(' >> result.lua
jq .versions[0].time version_manifest.json | sed 's/"//g' | tr '\n' ' ' >> result.lua
sed -i 's/ $//' result.lua
echo ')' >> result.lua
echo 'return {' >> result.lua
echo -en "\t[ '_meta.version' ] = \"" >> result.lua
jq .versions[0].id version_manifest.json | sed 's/"//g' | tr '\n' ' ' >> result.lua
sed -i 's/ $//' result.lua
echo "\"," >> result.lua

# Lua data table
grep -vP '^({|})$' en_us.json | sed -e 's/^\s*"//' -e 's/",*$//' -e 's/":\s*"/\t/g' | sort -V > en_us.list
grep -vP '^({|})$' zh_cn.json | sed -e 's/^\s*"//' -e 's/",*$//' -e 's/":\s*"/\t/g' | sort -V > zh_cn.list
grep -vP '^({|})$' zh_tw.json | sed -e 's/^\s*"//' -e 's/",*$//' -e 's/":\s*"/\t/g' | sort -V > zh_tw.list
grep -vP '^({|})$' zh_hk.json | sed -e 's/^\s*"//' -e 's/",*$//' -e 's/":\s*"/\t/g' | sort -V > zh_hk.list
diff <(cut -f1 en_us.list | sort -V | uniq) <(cat zh_cn.list | cut -f1 | sort -V | uniq) | grep -P '^<' | sed 's/^<\s*//' | grep -Ff - en_us.list | cat - zh_cn.list | sort -V > zh_cn; mv zh_cn zh_cn.list
diff <(cut -f1 en_us.list | sort -V | uniq) <(cat zh_tw.list | cut -f1 | sort -V | uniq) | grep -P '^<' | sed 's/^<\s*//' | grep -Ff - en_us.list | cat - zh_tw.list | sort -V > zh_tw; mv zh_tw zh_tw.list
diff <(cut -f1 en_us.list | sort -V | uniq) <(cat zh_hk.list | cut -f1 | sort -V | uniq) | grep -P '^<' | sed 's/^<\s*//' | grep -Ff - en_us.list | cat - zh_hk.list | sort -V > zh_hk; mv zh_hk zh_hk.list
join -t $'\t' en_us.list zh_cn.list | join -t $'\t' - zh_tw.list | join -t $'\t' - zh_hk.list | awk -F '\t' "{print \"\\t[ '\"\$1\"' ] = { \\\"\"\$2\"\\\", \\\"\"\$3\"\\\", \\\"\"\$4\"\\\", \\\"\"\$5\"\\\" },\"}" >> result.lua

# Lua footers
echo '}' >> result.lua

# Cleanup
rm *.json *.list *.jar
