#! /bin/bash
# NameProvider Data Generator, v2.1

# Prep
curl -Lo version_manifest.json https://piston-meta.mojang.com/mc/game/version_manifest.json
jq .versions[0].url version_manifest.json | xargs curl -Lo version.json
jq .downloads.client.url version.json | xargs curl -Lo client.jar
unzip client.jar assets/minecraft/lang/en_us.json
mv assets/minecraft/lang/en_us.json .
rm -r assets
jq .assetIndex.url version.json | xargs curl -Lo assets.json
jq .objects assets.json | jq 'to_entries|.[]|select(.key=="minecraft/lang/lzh.json")|.value' | jq .hash | sed 's/"//g' | awk '{print "curl -Lo lzh.json https://resources.download.minecraft.net/"substr($0,1,2)"/"$0}' | bash

# Lua headers
echo -n '-- version: ' > result.lua
jq .versions[0].id version_manifest.json | sed 's/"//g' >> result.lua
echo -n '-- asset: ' >> result.lua
jq .assetIndex.url version.json | sed 's/"//g' | tr '\n' ' ' >> result.lua
echo -n '(' >> result.lua
jq .versions[0].time version_manifest.json | sed 's/"//g' | tr '\n' ' ' >> result.lua
sed -i 's/ $//' result.lua
echo ')' >> result.lua
echo 'return {' >> result.lua
echo -en "\t[ '_meta.version' ] = \"" >> result.lua
jq .versions[0].id version_manifest.json | sed 's/"//g' | tr '\n' ' ' >> result.lua
sed -i 's/ $//' result.lua
echo "\"," >> result.lua

# Lua data table
grep -vP '^({|})$' en_us.json | sed -e 's/^\s*"//' -e 's/",*$//' -e 's/":\s*"/\t/g' | sort -V > en_us.list
grep -vP '^({|})$' lzh.json | sed -e 's/^\s*"//' -e 's/",*$//' -e 's/":\s*"/\t/g' | sort -V > lzh.list
diff <(cut -f1 en_us.list | sort -V | uniq) <(cat lzh.list | cut -f1 | sort -V | uniq) | grep -P '^<' | sed 's/^<\s*//' | grep -Ff - en_us.list | cat - lzh.list | sort -V > lzh; mv lzh lzh.list
join -t $'\t' en_us.list lzh.list | awk -F '\t' "{print \"\\t[ '\"\$1\"' ] = { \\\"\"\$2\"\\\", \\\"\"\$3\"\\\" },\"}" >> result.lua

# Lua footers
echo '}' >> result.lua

# Cleanup
rm *.json *.list *.jar
